# Generated by Django 5.2.7 on 2026-01-29 13:52

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addproperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('propertyName', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='properties/')),
                ('description', models.TextField(blank=True, null=True)),
                ('bedrooms', models.IntegerField(default=1)),
                ('bathrooms', models.IntegerField(default=1)),
                ('houseType', models.CharField(choices=[('apartment', 'Apartment'), ('bungalow', 'Bungalow'), ('duplex', 'Duplex')], default='apartment', max_length=20)),
                ('lga', models.CharField(choices=[('enugu-north', 'Enugu North'), ('enugu-south', 'Enugu South'), ('enugu-east', 'Enugu East')], default='Choose an lga', max_length=20)),
                ('Town', models.CharField(choices=[('gra', 'GRA'), ('independence layout', 'Independence Layout'), ('new layout', 'New Layout'), ('coal camp', 'Coal Camp'), ('ogui nike', 'Ogui Nike'), ('iva valley', 'Iva Valley'), ('holy ghost', 'Holy Ghost'), ('asata', 'Asata'), ('rangers avenue', 'Rangers Avenue'), ('uwani', 'Uwani'), ('maryland', 'Maryland'), ('gariki', 'Gariki'), ('achara layout', 'Achara Layout'), ('Agbani Road area', 'Agbani Road area'), ('kenyatta', 'Kenyatta'), ('abakpa', 'Abakpa'), ('trans-ekulu', 'Trans-Ekulu'), ('emene', 'Emene'), ('thinkers corner', 'Thinkers Corner'), ('liberty estate', 'Liberty Estate'), ('Nike lake', 'Nike Lake')], default='Choose the town', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Listproperties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('propertyName', models.CharField(max_length=100)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='')),
                ('bedrooms', models.IntegerField(default=1)),
                ('bathrooms', models.IntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('location', models.CharField(default='Enugu', max_length=100)),
                ('is_negotiable', models.BooleanField(default=True)),
                ('moreDescription', models.TextField(default='No additional description provided.', max_length=500)),
                ('contact_phone', models.CharField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('prop_size', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('houseType', models.CharField(choices=[('apartment', 'Apartment'), ('bungalow', 'Bungalow'), ('duplex', 'Duplex')], default='apartment', max_length=20)),
                ('prop_choices', models.CharField(choices=[('sale', 'Sale'), ('rent', 'Rent')], default='sale', max_length=20)),
                ('lga', models.CharField(choices=[('enugu-north', 'Enugu North'), ('enugu-south', 'Enugu South'), ('enugu-east', 'Enugu East')], default='Choose an lga', max_length=20)),
                ('Town', models.CharField(choices=[('gra', 'GRA'), ('independence layout', 'Independence Layout'), ('new layout', 'New Layout'), ('coal camp', 'Coal Camp'), ('ogui nike', 'Ogui Nike'), ('iva valley', 'Iva Valley'), ('holy ghost', 'Holy Ghost'), ('asata', 'Asata'), ('rangers avenue', 'Rangers Avenue'), ('uwani', 'Uwani'), ('maryland', 'Maryland'), ('gariki', 'Gariki'), ('achara layout', 'Achara Layout'), ('Agbani Road area', 'Agbani Road area'), ('kenyatta', 'Kenyatta'), ('abakpa', 'Abakpa'), ('trans-ekulu', 'Trans-Ekulu'), ('emene', 'Emene'), ('thinkers corner', 'Thinkers Corner'), ('liberty estate', 'Liberty Estate'), ('Nike lake', 'Nike Lake')], default='Choose the town', max_length=20)),
                ('duration', models.CharField(blank=True, choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default='select a timeframe', max_length=20, null=True)),
                ('status', models.CharField(blank=True, choices=[('approved', 'Approved'), ('pending', 'Pending'), ('declined', 'Declined')], default='pending', null=True)),
                ('reasonText', models.TextField(blank=True, max_length=250, null=True)),
                ('view_count', models.IntegerField(default=0)),
                ('prop_links', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='listing', to='Secur.addproperty')),
            ],
        ),
        migrations.CreateModel(
            name='Property_View',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('Propname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Secur.listproperties')),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_verified', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.BigIntegerField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')])),
                ('dob', models.DateField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OTPVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('otp_code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_used', models.BooleanField(default=False)),
                ('user_verification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('property_approved', 'Property Approved'), ('property_declined', 'Property Declined'), ('property_listed', 'Property Listed'), ('property_saved', 'Property Saved'), ('property_delisted', 'Property Delisted'), ('property_deleted', 'Property Deleted'), ('property_flagged', 'Property Flagged')], max_length=50)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Secur.listproperties')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='listproperties',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='addproperty',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='SavedProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Secur.listproperties')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'listing')},
            },
        ),
        migrations.AddIndex(
            model_name='listproperties',
            index=models.Index(fields=['lga', 'prop_choices'], name='Secur_listp_lga_f40c74_idx'),
        ),
        migrations.AddIndex(
            model_name='listproperties',
            index=models.Index(fields=['price'], name='Secur_listp_price_8ea8ed_idx'),
        ),
    ]
