# Generated by Django 5.2.7 on 2026-02-06 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Secur', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('property_uploaded', 'Property Uploaded'), ('property_approved', 'Property Approved'), ('property_declined', 'Property Declined'), ('property_listed', 'Property Listed'), ('property_saved', 'Property Saved'), ('property_unsaved', 'Property Unsaved'), ('property_delisted', 'Property Delisted'), ('property_deleted', 'Property Deleted'), ('property_flagged', 'Property Flagged')], max_length=50),
        ),
    ]
