# Generated by Django 5.2.7 on 2025-11-04 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Secur', '0002_addproperty'),
    ]

    operations = [
        migrations.AddField(
            model_name='addproperty',
            name='bathrooms',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='addproperty',
            name='bedrooms',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='addproperty',
            name='houseType',
            field=models.CharField(blank=True, choices=[('apartment', 'Apartment'), ('bungalow', 'Bungalow'), ('duplex', 'Duplex')], default='apartment', null=True),
        ),
    ]
