# Generated by Django 5.2.7 on 2026-02-09 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Secur', '0003_alter_listproperties_contact_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addproperty',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
