# Generated by Django 5.2.7 on 2025-11-04 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Secur', '0003_addproperty_bathrooms_addproperty_bedrooms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addproperty',
            name='houseType',
            field=models.CharField(choices=[('apartment', 'Apartment'), ('bungalow', 'Bungalow'), ('duplex', 'Duplex')], default='apartment', max_length=20),
        ),
    ]
