# Generated by Django 5.2.7 on 2025-11-06 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Secur', '0004_alter_addproperty_housetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='addproperty',
            name='contact_phone',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='addproperty',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='addproperty',
            name='is_negotiable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='addproperty',
            name='location',
            field=models.CharField(default='Enugu', max_length=100),
        ),
        migrations.AddField(
            model_name='addproperty',
            name='moreDescription',
            field=models.TextField(default='No additional description provided.', max_length=500),
        ),
        migrations.AddField(
            model_name='addproperty',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='addproperty',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='addproperty',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='properties/'),
        ),
    ]
