# Generated by Django 5.2.7 on 2025-11-06 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Secur', '0005_addproperty_contact_phone_addproperty_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='addproperty',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='properties/'),
        ),
        migrations.AddField(
            model_name='addproperty',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='properties/'),
        ),
    ]
