# Generated by Django 5.2.7 on 2025-11-07 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Secur', '0006_addproperty_image2_addproperty_image3'),
    ]

    operations = [
        migrations.AddField(
            model_name='addproperty',
            name='prop_size',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='addproperty',
            name='houseType',
            field=models.CharField(choices=[('apartment', 'Apartment'), ('bungalow', 'Bungalow'), ('duplex', 'Duplex'), ('land', 'Land')], default='apartment', max_length=20),
        ),
    ]
