# Generated by Django 5.2.7 on 2025-11-09 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Secur', '0007_addproperty_prop_size_alter_addproperty_housetype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listproperties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('propertyName', models.CharField(max_length=100)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='')),
                ('bedrooms', models.IntegerField(default=1)),
                ('bathrooms', models.IntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('location', models.CharField(default='Enugu', max_length=100)),
                ('is_negotiable', models.BooleanField(default=True)),
                ('moreDescription', models.TextField(default='No additional description provided.', max_length=500)),
                ('contact_phone', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('prop_size', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('houseType', models.CharField(choices=[('apartment', 'Apartment'), ('bungalow', 'Bungalow'), ('duplex', 'Duplex'), ('land', 'Land')], default='apartment', max_length=20)),
            ],
        ),
    ]
