# Generated by Django 5.2.7 on 2025-11-10 09:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Secur', '0008_listproperties'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addproperty',
            name='contact_phone',
        ),
        migrations.RemoveField(
            model_name='addproperty',
            name='email',
        ),
        migrations.RemoveField(
            model_name='addproperty',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='addproperty',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='addproperty',
            name='is_negotiable',
        ),
        migrations.RemoveField(
            model_name='addproperty',
            name='location',
        ),
        migrations.RemoveField(
            model_name='addproperty',
            name='moreDescription',
        ),
        migrations.RemoveField(
            model_name='addproperty',
            name='price',
        ),
        migrations.RemoveField(
            model_name='addproperty',
            name='prop_size',
        ),
        migrations.AddField(
            model_name='listproperties',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
