# Generated by Django 5.2.7 on 2025-11-10 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Secur', '0009_remove_addproperty_contact_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listproperties',
            name='prop_links',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Secur.addproperty'),
        ),
    ]
