# Generated by Django 5.2.7 on 2025-11-11 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Secur', '0010_listproperties_prop_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listproperties',
            name='contact_phone',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listproperties',
            name='prop_links',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Secur.addproperty'),
        ),
    ]
