# Generated by Django 5.2.7 on 2025-11-11 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Secur', '0011_alter_listproperties_contact_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listproperties',
            name='prop_links',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='listing', to='Secur.addproperty'),
        ),
    ]
