# Generated by Django 5.2.7 on 2025-11-11 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Secur', '0012_alter_listproperties_prop_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='listproperties',
            name='prop_choices',
            field=models.CharField(choices=[('sale', 'Sale'), ('rent', 'Rent')], default='sale', max_length=20),
        ),
    ]
