# Generated by Django 5.2.7 on 2025-11-12 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Secur', '0013_listproperties_prop_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='addproperty',
            name='Town',
            field=models.CharField(choices=[('gra', 'GRA'), ('independence layout', 'Independence Layout'), ('new layout', 'New Layout'), ('coal camp', 'Coal Camp'), ('ogui nike', 'Ogui Nike'), ('iva valley', 'Iva Valley'), ('holy ghost', 'Holy Ghost'), ('asata', 'Asata'), ('rangers avenue', 'Rangers Avenue'), ('uwani', 'Uwani'), ('maryland', 'Maryland'), ('gariki', 'Gariki'), ('achara layout', 'Achara Layout'), ('Agbani Road area', 'Agbani Road area'), ('kenyatta', 'Kenyatta'), ('abakpa', 'Abakpa'), ('trans-ekulu', 'Trans-Ekulu'), ('emene', 'Emene'), ('thinkers corner', 'Thinkers Corner'), ('liberty estate', 'Liberty Estate'), ('Nike lake', 'Nike Lake')], default='Choose the town', max_length=20),
        ),
        migrations.AddField(
            model_name='addproperty',
            name='lga',
            field=models.CharField(choices=[('enugu-north', 'Enugu North'), ('enugu-south', 'Enugu South'), ('enugu-east', 'Enugu East')], default='Choose an lga', max_length=20),
        ),
    ]
