# Generated by Django 5.2.7 on 2025-11-18 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Secur', '0015_listproperties_town_listproperties_lga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listproperties',
            name='houseType',
            field=models.CharField(choices=[('apartment', 'Apartment'), ('bungalow', 'Bungalow'), ('duplex', 'Duplex')], default='apartment', max_length=20),
        ),
    ]
