# Generated by Django 5.2.7 on 2025-11-18 14:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Secur', '0018_savedproperty'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='savedproperty',
            old_name='property',
            new_name='listing',
        ),
        migrations.AlterUniqueTogether(
            name='savedproperty',
            unique_together={('user', 'listing')},
        ),
    ]
