# Generated by Django 5.2.7 on 2025-11-26 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Secur', '0019_rename_property_savedproperty_listing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listproperties',
            name='duration',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default='How long', max_length=20),
        ),
    ]
