# Generated by Django 5.2.7 on 2025-11-26 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Secur', '0020_listproperties_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listproperties',
            name='duration',
            field=models.CharField(choices=[('rent', [('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')])], default='How long', max_length=20),
        ),
    ]
