# Generated by Django 5.2.7 on 2025-11-26 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Secur', '0021_alter_listproperties_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listproperties',
            name='duration',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default='select a timeframe', max_length=20),
        ),
    ]
