# Generated by Django 5.2.7 on 2025-11-26 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Secur', '0022_alter_listproperties_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listproperties',
            name='duration',
            field=models.CharField(blank=True, choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default='select a timeframe', max_length=20, null=True),
        ),
    ]
