# Generated by Django 5.2.7 on 2025-11-27 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Secur', '0023_alter_listproperties_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='listproperties',
            name='reasonText',
            field=models.TextField(blank=True, default='Wrong images', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='listproperties',
            name='status',
            field=models.CharField(blank=True, choices=[('approved', 'Approved'), ('pending', 'Pending'), ('declined', 'Declined')], null=True),
        ),
    ]
