# Generated by Django 5.2.7 on 2025-11-27 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Secur', '0024_listproperties_reasontext_listproperties_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listproperties',
            name='status',
            field=models.CharField(blank=True, choices=[('approved', 'Approved'), ('pending', 'Pending'), ('declined', 'Declined')], default='pending', null=True),
        ),
    ]
