# Generated by Django 5.2.7 on 2025-12-16 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Secur', '0025_alter_listproperties_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='listproperties',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
