# Generated by Django 5.2.7 on 2025-12-17 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Secur', '0026_listproperties_view_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property_View',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('Propname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Secur.listproperties')),
            ],
        ),
    ]
