# Generated by Django 5.2.7 on 2026-01-03 22:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Secur', '0027_property_view'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='listproperties',
            index=models.Index(fields=['lga', 'prop_choices'], name='Secur_listp_lga_f40c74_idx'),
        ),
        migrations.AddIndex(
            model_name='listproperties',
            index=models.Index(fields=['price'], name='Secur_listp_price_8ea8ed_idx'),
        ),
    ]
